### ISSUE TITLE
前面の板に隙間がある

### ISSUE THREAD

**Issue by yasuohayashibara** [tadanohiroyuki/panel-type-scalar-arm#1]
前面の板に隙間があります．

![image](https://user-images.githubusercontent.com/5755200/203874557-b3c36d5f-27d2-459e-8afc-e3aa1128dc82.png)

**Comment by tadanohiroyuki** [comment]
隙間埋めて回転する際干渉する部分面取りしました

**Comment by yasuohayashibara** [comment]
こちらもアップロードして下さい．

**Comment by tadanohiroyuki** [comment]
アップロードしました.

**Comment by yasuohayashibara** [comment]
ずれています．

![image](https://user-images.githubusercontent.com/5755200/204133223-2efd2290-1861-41c0-aac9-154d39f7ac54.png)

**Comment by tadanohiroyuki** [comment]
改良しました

**Comment by yasuohayashibara** [comment]
確認しました．
issueを閉じます．

![image](https://user-images.githubusercontent.com/5755200/206351552-e614ff54-f131-4660-8b4e-b2b3cc56268e.png)
