### ISSUE TITLE
根本を駆動するモータ

### ISSUE THREAD

**Issue by yasuohayashibara** [tadanohiroyuki/panel-type-scalar-arm#2]
根本関節を駆動するモータは１つで良いと思います．
一つは受動関節で良いと思います．

![image](https://user-images.githubusercontent.com/5755200/203874695-5fc7ef39-751d-4848-b2ef-2c8145a34510.png)

**Comment by tadanohiroyuki** [comment]
まだ具体的なアイディア設計には取り入れられてないです.
受動関節の良い方法模索中です.

**Comment by yasuohayashibara** [comment]
表現間違っていましたが，動力の無い受動的な部品となります．
軸とベアリングがあれば良いと思います．

**Comment by tadanohiroyuki** [comment]
下のサーボモータ取り外して設計変更してみます.
現状,軸（シャフト）とサーボモータ固定する方法がわからないです.そもそも固定する必要ないでしょうか.

**Comment by yasuohayashibara** [comment]
質問が分かりません．
他の機構ではどうしているか調査したほうが良いと思います．
林原としては上記で示したように軸とベアリングで回転する関節を設計すれば良いと思います．
簡単な図を書いて質問をしてくれるとアドバイスできると思います．

**Comment by tadanohiroyuki** [comment]
追加しました.

**Comment by yasuohayashibara** [comment]
ベアリングが２つ使用されています．
一般的には下はベアリングではなく軸をフレームに固定すると思います．

![image](https://user-images.githubusercontent.com/5755200/206352092-b270f31c-1682-402f-8718-d09c4e76f405.png)

**Comment by tadanohiroyuki** [comment]
ベアリング一個に変更し下のアルミフレームとシャフトを固定しました

**Comment by yasuohayashibara** [comment]
はい．
issueを閉じます．

![image](https://user-images.githubusercontent.com/5755200/207357155-5424a080-d211-4cd2-8c4d-b549a3b3f9fe.png)
