### ISSUE TITLE
板同士の接合方法

### ISSUE THREAD

**Issue by yasuohayashibara** [tadanohiroyuki/panel-type-scalar-arm#3]
板同士の接合方法が示されていません．

![image](https://user-images.githubusercontent.com/5755200/203874814-1d43091b-24ce-4e61-b884-98bf9eb15208.png)

**Comment by tadanohiroyuki** [comment]
ここの接合方法はどうしたらいいでしょうか？
L字金具しか思い浮かばないです.他に方法がないか今からホームセンター行って見てきます.

**Comment by yasuohayashibara** [comment]
この板材の素材と加工法で取れる手段が変わります．
ちなみに，L字金具の場合，モータの取り付け用のコの字型の部品と干渉しそうな気がします．
何かを入れるスペースは残っていなさそうな気がします．

![image](https://user-images.githubusercontent.com/5755200/203983546-45cbba00-b3d8-49c6-a3c4-831872e2f80a.png)

**Comment by tadanohiroyuki** [comment]
アルミの長いフラットバーを買って,枠のサイズ合わせて4本に切っていくのが早いのかなと考えていました.

L字金具の場合入れるスペース作ります.

**Comment by yasuohayashibara** [comment]
フラットバーとは角柱のことでしょうか．
上下（前後）の板もそれで固定するということですね．

**Comment by tadanohiroyuki** [comment]
そうです.
[https://nikkal.net/archives/2009/04/post-56.html](url)

他に手段なさそうでしたらそれで固定してみます.

**Comment by yasuohayashibara** [comment]
具体的にどう固定するのか知りたいので図面に反映させて下さい．

**Comment by tadanohiroyuki** [comment]
アルミフレームに変更しました.

**Comment by yasuohayashibara** [comment]
大きな穴が貫通しているので，ネジで固定できないと思います．

![image](https://user-images.githubusercontent.com/5755200/206352798-e8555f2e-ed4b-4bce-8140-f334d0a0e4ac.png)

**Comment by tadanohiroyuki** [comment]
ザグリ穴を追加工します.設計に反映させました.

**Comment by yasuohayashibara** [comment]
変更した部分をできれば画像で付けて下さい．
反映されていないように見えます．

![image](https://user-images.githubusercontent.com/5755200/207357860-b72ab296-ca21-4291-ac4b-ab94c8deecd4.png)

**Comment by yasuohayashibara** [comment]
別件の板同士の接合ということでは，前のパネルをどのように接合するのかが示されていません．

![image](https://user-images.githubusercontent.com/5755200/207358357-f78dfa88-8496-4b70-a9a2-d86201027802.png)

**Comment by yasuohayashibara** [comment]
部品リストを見るとレンチ穴を開けていますが，これを利用して固定するためには専用の部品が必要です．
HFSF5-2040-180-LWH-RWH

全てをチェックしきれたわけではありませんが，もしこれを採用するのであれば固定用の部品が必要です．

以下のページのレンチ穴を参照
https://jp.misumi-ec.com/special/alumiframe/additional_machining/detail/

**Comment by tadanohiroyuki** [comment]
MISUMIのアルミフレーム加工サービスをレンチ穴からザグリ穴に変更しました．ねじ固定問題は解決できたかと思います．

<img width="229" alt="スクリーンショット 2022-12-15 011227" src="https://user-images.githubusercontent.com/71136994/207648440-c8c7474d-b5e4-4341-9d5f-d9cb0ac9a8dd.png">
<img width="440" alt="スクリーンショット 2022-12-15 011429" src="https://user-images.githubusercontent.com/71136994/207648915-bfd555cf-afc9-4476-b79f-1a3577d13813.png">

**Comment by tadanohiroyuki** [comment]
ここはカバーとしての役割しかないため簡易的な接着，両面テープを使用するのはありでしょうか．

> 別件の板同士の接合ということでは，前のパネルをどのように接合するのかが示されていません．
> 
> ![image](https://user-images.githubusercontent.com/5755200/207358357-f78dfa88-8496-4b70-a9a2-d86201027802.png)

**Comment by tadanohiroyuki** [comment]
先輩からアドバイス頂きまして変更しております。
設計に反映でき次第gitの方の設計更新します。

**Comment by tadanohiroyuki** [comment]
設計更新しました
<img width="505" alt="スクリーンショット 2022-12-17 123933" src="https://user-images.githubusercontent.com/71136994/208222000-0aeab92a-6d9f-4286-abf6-a01dd35507f0.png">
<img width="503" alt="スクリーンショット 2022-12-17 123941" src="https://user-images.githubusercontent.com/71136994/208222002-8f27961f-1def-4e7f-83c1-13d893134542.png">

**Comment by yasuohayashibara** [comment]
> ここはカバーとしての役割しかないため簡易的な接着，両面テープを使用するのはありでしょうか．

あまり感心できない方法ですが，時間が無いのでこちらを採用しましょう．
issueを閉じます．
