### ISSUE TITLE
サーボモータと板との接合方法

### ISSUE THREAD

**Issue by yasuohayashibara** [tadanohiroyuki/panel-type-scalar-arm#4]
サーボモータと板との接合方法が示されていません．

![image](https://user-images.githubusercontent.com/5755200/203875776-acf8fa9e-31bb-4fe9-9447-182b79a22fa2.png)

**Comment by tadanohiroyuki** [comment]
サーボホーンとアームをネジ止め固定します.アームに固定用の穴を空けていなかったため空けます.

**Comment by yasuohayashibara** [comment]
確認しますのでデータをアップロードして下さい．

**Comment by tadanohiroyuki** [comment]
こちらもアップロードしました.

**Comment by yasuohayashibara** [comment]
#7 で述べたことですが，こちらの議論につながるissueですので，こちらに移動します．

サーボモータの出力とは反対側の軸の固定方法ですが，２つの点で問題があります．

１）ベアリングが無いので滑りません．

２）矢印方向に少しでも力が加わるとプラスチックがたわんで外れます．
　　逆にたわまない場合は組立てが組立てが難しいかもしれません．

![image](https://user-images.githubusercontent.com/5755200/204133676-568fb0e2-fd66-47ac-a764-5859dc2e3018.png)

問題となる部分
![image](https://user-images.githubusercontent.com/5755200/204133536-9ddaad34-2459-43d6-abc8-03ba8cbc3b17.png)

この穴で支えるのは難しいと思います．
![image](https://user-images.githubusercontent.com/5755200/204133541-82444ccc-ff84-4561-95a7-c4d327cda7ef.png)

**Comment by yasuohayashibara** [comment]
ちなみに，B3Mサーボモータには出力と反対の軸を固定するための部品もあります．
このような場合は一般的にはこの部品を使います．

ちなみに，出力と反対の方向に軸が出ていますが，この部品を取り付けるための突起です．

https://kondo-robot.com/product/02137

**Comment by tadanohiroyuki** [comment]
追加しました.

**Comment by yasuohayashibara** [comment]
確認しました．
issueを閉じます．
