### ISSUE TITLE
ネジの隙間

### ISSUE THREAD

**Issue by yasuohayashibara** [tadanohiroyuki/panel-type-scalar-arm#5]
ネジの隙間が充分かを確認して下さい．
ネジの頭が干渉している場合は，設計を変更することが必要となります．

![image](https://user-images.githubusercontent.com/5755200/203875862-e6d8c233-6994-4793-bf6b-168bdf1b5d4e.png)

**Comment by tadanohiroyuki** [comment]
2mmほどの隙間しかなかったため3mmに拡張しました.

**Comment by yasuohayashibara** [comment]
新しいデータがアップロードされていませんので，アップロードして下さい．

**Comment by tadanohiroyuki** [comment]
こちらもアップロードしました

**Comment by yasuohayashibara** [comment]
3mmであることを確認しました．
issueを閉じます．
